In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\rutuj\Downloads\DSDBA\dataset_Facebook.csv",sep=';')

In [5]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [6]:
df.shape

(500, 19)

In [7]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Page total likes                                                     500 non-null    int64
 1   Type                                                                 500 non-null    object
 2   Category                                                             500 non-null    int64
 3   Post Month                                                           500 non-null    int64
 4   Post Weekday                                                         500 non-null    int64
 5   Post Hour                                                            500 non-null    int64
 6   Paid                                                                 499 non-null    float64
 7   Lifetime Post Total Reach                                            500 non-null    int64
 8   Lifetime Post Total Impressions                                      500 non-null    int64
 9   Lifetime Engaged Users                                               500 non-null    int64
 10  Lifetime Post Consumers                                              500 non-null    int64
 11  Lifetime Post Consumptions                                           500 non-null    int64
 12  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 13  Lifetime Post reach by people who like your Page                     500 non-null    int64
 14  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 15  comment                                                              500 non-null    int64
 16  like                                                                 499 non-null    float64
 17  share                                                                496 non-null    float64
 18  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

In [10]:
df.dtypes

Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page                         int64
Lifetime People who have liked your Page and engaged with your post      int64
comment                                                                  int64
like                                                                   float64
share                                                                  float64
Total Interactions                                                       int64
dtype: object

In [11]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [12]:
#Creating data subset

subset1 = df[['Type','Category','like']]
subset1

       Type  Category    like
0     Photo         2    79.0
1    Status         2   130.0
2     Photo         3    66.0
3     Photo         2  1572.0
4     Photo         2   325.0
..      ...       ...     ...
495   Photo         3    53.0
496   Photo         2    53.0
497   Photo         1    93.0
498   Photo         3    91.0
499   Photo         2    91.0

[500 rows x 3 columns]

In [13]:
subset2 = df.iloc[0:50]
subset2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
30,138895,Photo,2,12,4,2,0.0,4940,9390,385,306,501,5860,2930,273,33,107.0,22.0,162
31,138895,Photo,2,12,3,10,0.0,1683,2929,192,171,221,1585,858,131,1,27.0,11.0,39
32,138895,Photo,3,12,3,3,0.0,5280,9578,368,237,345,4480,2422,268,2,155.0,47.0,204
33,138895,Photo,3,12,2,9,0.0,3002,5318,268,185,247,3039,1676,194,4,98.0,23.0,125
34,138895,Photo,1,12,2,3,0.0,3766,7149,298,260,431,5782,2938,244,2,56.0,17.0,75
35,138895,Photo,2,12,1,11,0.0,4512,7808,423,284,431,5183,2954,316,6,172.0,21.0,199
36,138895,Photo,3,12,1,3,0.0,2690,4628,252,168,226,3052,1727,199,0,96.0,17.0,113
37,138895,Photo,1,12,7,10,1.0,19800,28663,479,424,805,5187,2752,248,16,76.0,8.0,100
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
39,138895,Photo,1,12,7,3,0.0,3290,6085,306,284,402,4986,2584,247,1,44.0,14.0,59
40,138895,Status,2,12,6,11,0.0,13280,24198,2055,1912,2720,17627,9344,1716,7,216.0,39.0,262
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
42,138353,Photo,1,12,5,10,0.0,7268,13989,2087,2079,12074,13544,7096,1975,7,26.0,3.0,36
43,138353,Link,1,12,5,3,1.0,2645,4270,134,109,170,2330,1377,101,7,29.0,10.0,46
44,138353,Photo,1,12,4,11,0.0,4284,8387,355,316,513,7283,3634,291,0,47.0,11.0,58
45,138353,Link,1,12,4,3,1.0,7968,13023,206,158,223,6734,3492,138,4,57.0,10.0,71
46,138353,Status,1,12,3,11,0.0,16576,30612,3572,3464,4802,24363,12888,3014,4,174.0,36.0,214
47,138353,Link,1,12,3,2,0.0,1925,3481,97,83,126,2307,1180,77,6,18.0,8.0,32
48,138353,Photo,1,12,2,11,0.0,3786,7329,338,283,450,6336,3216,280,0,77.0,15.0,92
49,138353,Link,1,12,2,2,0.0,1536,3094,84,76,99,2903,1407,76,1,12.0,1.0,14

In [14]:
subset3 = df[df['like']>500]
print(subset3[['Type','like']])

       Type    like
3     Photo  1572.0
14    Photo   577.0
17    Photo   678.0
28    Photo   523.0
67    Photo   697.0
101   Photo  1505.0
105   Photo   955.0
142  Status   859.0
168   Photo  1622.0
176   Photo  1047.0
191   Photo   766.0
199   Photo  1155.0
206   Photo   859.0
240   Photo   535.0
244   Photo  5172.0
254   Photo   755.0
264   Photo   529.0
270   Photo   696.0
272   Photo   534.0
323   Photo  1372.0
328   Photo   617.0
346   Photo   821.0
349   Photo  1639.0
379   Photo  1998.0
391   Photo   766.0
442   Photo   664.0
460   Photo  1546.0
476   Photo   579.0

In [15]:
subset4 = df[df['Paid']==1]
print(subset4[['Type','Paid']])

      Type  Paid
3    Photo   1.0
6    Photo   1.0
7    Photo   1.0
14   Photo   1.0
17   Photo   1.0
..     ...   ...
473  Photo   1.0
475  Photo   1.0
476  Photo   1.0
481   Link   1.0
491  Photo   1.0

[139 rows x 2 columns]

In [16]:
subset5 = df[df['Type']=='Photo']
print(subset5[['Type', 'like', 'comment']])

      Type    like  comment
0    Photo    79.0        4
2    Photo    66.0        0
3    Photo  1572.0       58
4    Photo   325.0       19
6    Photo   249.0        3
..     ...     ...      ...
495  Photo    53.0        5
496  Photo    53.0        0
497  Photo    93.0        4
498  Photo    91.0        7
499  Photo    91.0        0

[426 rows x 3 columns]

In [17]:
#merge data
merged_columns = pd.merge(subset1, subset3, on='Type', how='inner')
merged_columns

,Type,Category_x,like_x,Page total likes,Category_y,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,...,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like_y,share,Total Interactions
0,Photo,2,79.0,139441,2,12,2,10,1.0,50128,...,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
1,Photo,2,79.0,138414,2,12,4,5,1.0,22784,...,887,337,417,34415,19312,684,2,577.0,20.0,599
2,Photo,2,79.0,138414,1,12,2,12,1.0,53264,...,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
3,Photo,2,79.0,138895,2,12,5,3,0.0,9560,...,973,559,885,9217,4748,621,36,523.0,63.0,622
4,Photo,2,79.0,138185,1,11,7,3,1.0,53456,...,1576,995,1469,32646,14912,884,20,697.0,70.0,787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11542,Photo,2,91.0,111620,3,4,1,14,1.0,105632,...,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
11543,Photo,2,91.0,109670,2,4,1,13,1.0,32208,...,1933,1367,2123,43980,24720,1568,6,766.0,109.0,881
11544,Photo,2,91.0,98195,3,3,4,13,0.0,34480,...,1591,1156,1926,184270,30720,1292,10,664.0,97.0,771
11545,Photo,2,91.0,92507,3,2,1,13,0.0,55520,...,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
11546,Photo,2,91.0,86909,1,1,6,10,1.0,37088,...,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633

In [18]:
subset1 = subset1.reset_index(drop=True)
subset3 = subset3.reset_index(drop=True)

merged_rows = pd.concat([subset1, subset3], axis=0, ignore_index=True)

In [19]:
#sort data

Sorted_subset3 = subset3.sort_values(by='like',ascending=False)
print(Sorted_subset3[['Type','like']])

      Type    like
14   Photo  5172.0
23   Photo  1998.0
22   Photo  1639.0
8    Photo  1622.0
0    Photo  1572.0
26   Photo  1546.0
5    Photo  1505.0
19   Photo  1372.0
11   Photo  1155.0
9    Photo  1047.0
6    Photo   955.0
7   Status   859.0
12   Photo   859.0
21   Photo   821.0
10   Photo   766.0
24   Photo   766.0
15   Photo   755.0
4    Photo   697.0
17   Photo   696.0
2    Photo   678.0
25   Photo   664.0
20   Photo   617.0
27   Photo   579.0
1    Photo   577.0
13   Photo   535.0
18   Photo   534.0
16   Photo   529.0
3    Photo   523.0

In [20]:
#transpose data

trans = subset4.T
trans

,3,6,7,14,17,29,37,41,43,45,...,459,462,463,466,467,473,475,476,481,491
Page total likes,139441,139441,139441,138414,138414,138895,138895,138895,138353,138353,...,92614,92293,92186,91865,91758,91116,86909,86909,86491,85979
Type,Photo,Photo,Photo,Photo,Photo,Video,Photo,Link,Link,Link,...,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Photo,Link,Photo
Category,2,3,3,2,1,1,1,1,1,1,...,2,3,3,2,2,3,3,1,1,3
Post Month,12,12,12,12,12,12,12,12,12,12,...,2,2,2,2,2,2,1,1,1,1
Post Weekday,2,1,7,4,2,4,7,6,5,4,...,2,7,7,5,5,2,6,6,4,6
Post Hour,10,3,9,5,12,11,10,3,3,3,...,3,13,2,13,3,4,16,10,4,3
Paid,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Lifetime Post Total Reach,50128,11692,13720,22784,53264,36208,19800,18480,2645,7968,...,5290,10040,153536,4840,15880,7132,5754,37088,4938,6184
Lifetime Post Total Impressions,87991,19479,24137,39941,111785,61262,28663,28438,4270,13023,...,9100,17029,497910,7466,51571,12060,9238,10966,7910,10228
Lifetime Engaged Users,2211,481,537,887,1706,1141,479,517,134,206,...,1053,1429,1713,949,1188,1004,1179,2728,66,956
Lifetime Post Consumers,790,265,232,337,1103,1068,424,366,109,158,...,994,1346,1633,923,1071,944,1143,2288,63,901
Lifetime Post Consumptions,1119,364,305,417,1655,1728,805,460,170,223,...,1326,2022,2493,1116,1410,1226,1452,3183,70,1140
Lifetime Post Impressions by people who have liked your Page,61027,15432,19728,34415,92512,30131,5187,12078,2330,6734,...,6285,11744,8907,5362,47976,8294,6101,66311,6625,6085
Lifetime Post reach by people who like your Page,32048,9328,11056,19312,39776,14112,2752,6752,1377,3492,...,3578,6964,5696,3370,13560,4736,3546,34352,3804,3502
Lifetime People who have liked your Page and engaged with your post,1386,379,422,684,1307,559,248,319,101,138,...,441,742,593,447,677,576,420,2021,59,437
comment,58,3,0,2,15,18,16,6,7,4,...,2,19,8,3,1,4,0,7,0,1
like,1572.0,249.0,325.0,577.0,678.0,143.0,76.0,187.0,29.0,57.0,...,129.0,214.0,134.0,47.0,200.0,136.0,65.0,579.0,5.0,105.0
share,147.0,27.0,14.0,20.0,20.0,13.0,8.0,18.0,10.0,10.0,...,32.0,78.0,34.0,21.0,37.0,42.0,19.0,47.0,2.0,46.0
Total Interactions,1777,279,339,599,713,174,100,211,46,71,...,163,311,176,71,238,182,84,633,7,152

In [21]:
#reshaping

data_array = df.values
total_elements = data_array.size
reshaped_data = data_array.reshape(100, int(total_elements/100))
print("Original Shape:", df.shape)
print("Reshaped Shape:", reshaped_data.shape)

Original Shape: (500, 19)
Reshaped Shape: (100, 95)

In [22]:
#pivot table

pivot_table = pd.pivot_table(df, values='like',index='Type',aggfunc='mean')
pivot_table

              like
Type
Link     73.318182
Photo   182.611765
Status  176.711111
Video   231.428571